backend:
  name: github
  repo: JKatras/test-gridsome-site
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts" #Post type identifier, used in routes. Must be unique
    label: "Posts" #What the admin UI calls the post type
    folder: "static/posts" #Where files of this type are stored, relative to the repo root
    create: true #Allow users to create new files in this collection
    slug: "{{slug}}" #Filename template, e.g., YYYY-MM-DD_title.md
    fields: #Fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} #
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}